sudo: required
services:
  - docker


before_install:
  - gem install rails
  - docker build -t akif05/docker-react -f Dockerfile.dev .

script:
  - docker run akif05/docker-react npm run test -- --coverage

# Tell Travis we need a copy of docker running
#sudo: required
#services:
#  - docker

# Build our image using Dockerfile.dev
#before_intall:
#  - docker build -t akif05/docker-react -f Dockerfile.dev --no-cache .

# Tell Travis how to run our test suite
# script section defines all commands to run test
# our 'npm run test' will wait for input, that's why we
# need to add '-- --coverage'
# with this 'npm run test' will automaticaly exit
#script:
#  - docker run akif05/docker-react npm run test -- --coverage

